name: journal-article

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Manual trigger'
        
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
  job_id:
    timeout-minutes: 10
    name: journal-article
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script
      env:
        USER_AGENT: ${{ secrets.USER_AGENT }}
      run: |
        python src/ideas_repec.py --author 50 --timeout 5 --sleep 1 --user_agent ${USER_AGENT} --index 1 --column journal_article --value "Total Journal Articles" --file_name "./data/journal-article.zip"
    - name: Commit changes
      env:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_NAME: ${{ secrets.USER_NAME }}
      run: |
        git config --global user.email ${USER_EMAIL}
        git config --global user.name ${USER_NAME}
        git remote set-url origin https://${USER_NAME}:${ACCESS_TOKEN}@github.com/${USER_NAME}/ideas-repec.git
        git add data/journal-article.zip
        git commit -m "Added/modified journal article data"
        git pull --rebase origin main
        git push -u origin main
